# Generated by Django 4.0.2 on 2022-02-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
    ]
