# Generated by Django 4.0.2 on 2022-02-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_rename_name_users_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
