# Generated by Django 4.0.2 on 2022-03-06 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
