# Generated by Django 4.0.2 on 2022-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_statustask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='task',
            field=models.BooleanField(default=True),
        ),
    ]
