# Generated by Django 4.0.2 on 2022-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_statustask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statustask',
            name='task',
        ),
        migrations.AlterField(
            model_name='statustask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
