# Generated by Django 4.0.2 on 2022-03-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_remove_statustask_task_alter_statustask_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustask',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
