# Generated by Django 4.0.2 on 2022-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_task_executor_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='statustask',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
