# Generated by Django 4.0.2 on 2022-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0013_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(to='task_manager.Label'),
        ),
    ]
