# Generated by Django 4.0.2 on 2022-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0016_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_manager.Label'),
        ),
    ]
