# Generated by Django 4.0.2 on 2022-03-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0019_userapp_alter_task_autor_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApp',
        ),
    ]
