# Generated by Django 4.0.2 on 2022-03-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0022_user_delete_userapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
